"""The world on 1 January 1836, for build_1836.py (ROADMAP.md section 3 and
Appendix A). Borders start from the 1815 polities of historical-basemaps and
are corrected by RULES, which run in order (the last match wins) and select
land by modern country (C), admin-1 region (A), 1815 polity (P) or a lon/lat
box (B: west, south, east, north). Tag "-" leaves land unowned.
"""

# tag: (name, colour or None for a generated one, flag file in resources/flags or None)
NATIONS = {
    # Great powers
    "GBR": ("United Kingdom", "#c8102e", "gb"),
    "FRA": ("France", "#2b4c9b", "Kingdom of France"),
    "RUS": ("Russian Empire", "#3f7f3f", "Romanov Russia"),
    "AUS": ("Austrian Empire", "#e8d44d", "Habsburg Austria"),
    "PRU": ("Prussia", "#3c4a5a", "prussia"),
    "OTT": ("Ottoman Empire", "#86a15a", "Ottoman Empire"),
    # Europe
    "SPA": ("Spain", "#f2b632", "es"),
    "CAR": ("Carlists", "#8c1d18", None),
    "POR": ("Portugal", "#2e8b57", "kingdom_of_portugal"),
    "NED": ("Netherlands", "#ff9f1a", "nl"),
    "BEL": ("Belgium", "#b5892a", "be"),
    "LUX": ("Luxembourg", "#6fa8dc", "lu"),
    "SWI": ("Switzerland", "#d9534f", "ch"),
    "DEN": ("Denmark", "#b03a2e", "dk"),
    "SWE": ("Sweden", "#3b6fb6", "Sweden-Norway (1836)"),
    "NOR": ("Norway", "#c46a6a", "no"),
    "FIN": ("Grand Duchy of Finland", "#b7c9e2", "Grand Duchy of Finland"),
    "POL": ("Congress Poland", "#d98c9a", "pl"),
    "KRA": ("Free City of Kraków", "#e3a1b0", None),
    "GRE": ("Greece", "#5b92e5", "gr"),
    "SER": ("Serbia", "#9e4b4b", "rs"),
    "WAL": ("Wallachia", "#d4a017", None),
    "MOL": ("Moldavia", "#c06c2c", "Principality of Moldavia"),
    "MON": ("Montenegro", "#7a3b69", "me"),
    "SAR": ("Kingdom of Sardinia", "#6aa6d9", "Kingdom of Sardinia"),
    "PMA": ("Duchy of Parma", "#e8a0c8", "Duchy of Parma"),
    "MOD": ("Duchy of Modena", "#7fb7a4", "Duchy of Modena and Reggio"),
    "LUC": ("Duchy of Lucca", "#c9b458", None),
    "TUS": ("Grand Duchy of Tuscany", "#9b59b6", "Grand Duchy of Tuscany"),
    "PAP": ("Papal States", "#efe3b8", "PapalStates"),
    "SMR": ("San Marino", "#8ecae6", "sm"),
    "SIC": ("Two Sicilies", "#a9d18e", "TwoSicilies"),
    # German Confederation
    "BAV": ("Bavaria", "#87ceeb", "DE-BY"),
    "WUR": ("Württemberg", "#c9a227", "DE-BW"),
    "BAD": ("Baden", "#e0b84c", None),
    "SAX": ("Saxony", "#2f9e44", "DE-SN"),
    "HAN": ("Hanover", "#d6d6c2", "DE-NI"),
    "HKA": ("Hesse-Kassel", "#b56576", "DE-HE"),
    "HDA": ("Hesse-Darmstadt", "#e56b6f", None),
    "NAS": ("Nassau", "#eaac8b", None),
    "BRU": ("Brunswick", "#6d597a", None),
    "OLD": ("Oldenburg", "#355070", None),
    "MEC": ("Mecklenburg-Schwerin", "#4d908e", "DE-MV"),
    "MST": ("Mecklenburg-Strelitz", "#577590", None),
    "THU": ("Saxon Duchies", "#90be6d", "DE-TH"),
    "ANH": ("Anhalt", "#43aa8b", "DE-ST"),
    "LIP": ("Lippe", "#f9c74f", None),
    "WDK": ("Waldeck", "#f8961e", None),
    "HOH": ("Hohenzollern", "#adb5bd", None),
    "HAM": ("Hamburg", "#e63946", "DE-HH"),
    "BRE": ("Bremen", "#f28482", "DE-HB"),
    "LUB": ("Lübeck", "#f6bd60", None),
    "FRK": ("Frankfurt", "#84a59d", None),
    # Americas
    "USA": ("United States", "#4a7bd0", "USA 1776"),
    "TEX": ("Texas", "#9d4edd", "Texas"),
    "MEX": ("Mexico", "#1e6f5c", "mx"),
    "UCA": ("Central America", "#4ea8de", "Federal Republic of Central America"),
    "MSQ": ("Mosquito Coast", None, "Mosquito Kingdom"),
    "HAI": ("Haiti", "#3d5a80", "ht"),
    "NGR": ("New Granada", "#ffd166", "co"),
    "VEN": ("Venezuela", "#ef8a62", "ve"),
    "ECU": ("Ecuador", "#f6e27f", "ec"),
    "PER": ("Peru", "#e76f51", "pe"),
    "BOL": ("Bolivia", "#f4a261", "bo"),
    "CHL": ("Chile", "#b3261e", "cl"),
    "ARG": ("Argentine Confederation", "#8ecae6", "ar"),
    "URU": ("Uruguay", "#90e0ef", "uy"),
    "PGY": ("Paraguay", "#a7c957", "py"),
    "BRZ": ("Empire of Brazil", "#7cb342", "br"),
    "COM": ("Comanchería", None, None),
    "LAK": ("Lakota", None, "Lakotah"),
    "SEM": ("Seminole", None, None),
    "MAP": ("Mapuche", None, "La Araucania"),
    # North Africa and the Middle East
    "MOR": ("Morocco", "#a4133c", "ma"),
    "ABD": ("Emirate of Abdelkader", "#6a994e", None),
    "CON": ("Beylik of Constantine", "#bc6c25", None),
    "TUN": ("Tunis", "#c1121f", "tn"),
    "EGY": ("Egypt", "#d8b25c", "Kingdom of Egypt"),
    "NEJ": ("Nejd", "#606c38", "Sultanate of Nejd"),
    "YEM": ("Yemen", "#bb9457", "Kingdom of Yemen"),
    "LAH": ("Lahej", None, "Sultanate of Lahej"),
    "HAD": ("Hadhramaut", None, "Kathiri State"),
    "OMA": ("Oman", "#9e2a2b", "om"),
    "TRU": ("Trucial Sheikhdoms", None, "Trucial States"),
    "BAH": ("Bahrain", None, "bh"),
    "KUW": ("Kuwait", None, "kw"),
    "PRS": ("Persia", "#3aa39a", "Persia"),
    "IMA": ("Caucasian Imamate", None, None),
    # Central and South Asia
    "AFG": ("Emirate of Kabul", "#7f5539", "Emirate of Afghanistan"),
    "HER": ("Herat", None, None),
    "KDH": ("Kandahar", None, None),
    "KUN": ("Kunduz", None, None),
    "KHI": ("Khiva", None, "Khiva"),
    "BUK": ("Bukhara", "#588157", "Bukhara"),
    "KOK": ("Kokand", None, None),
    "KZH": ("Kazakh Senior Horde", None, "Kazakh Khanate"),
    "PUN": ("Sikh Empire", "#e09f3e", None),
    "SND": ("Sindh", None, None),
    "BHW": ("Bahawalpur", None, None),
    "KAL": ("Kalat", None, None),
    "EIC": ("East India Company", "#d2691e", None),
    "HYD": ("Hyderabad", "#ffb703", None),
    "OUD": ("Oudh", None, None),
    "MYS": ("Mysore", None, None),
    "TRV": ("Travancore", None, None),
    "GWA": ("Gwalior", None, None),
    "HOL": ("Indore", None, None),
    "BAR": ("Baroda", None, None),
    "NAG": ("Nagpur", None, None),
    "BHO": ("Bhopal", None, None),
    "RAJ": ("Rajputana", "#e5989b", None),
    "NEP": ("Nepal", "#9d0208", "np"),
    "BHU": ("Bhutan", None, "bt"),
    "SIK": ("Sikkim", None, "Sikkim"),
    "MNP": ("Manipur", None, None),
    # East and Southeast Asia
    "QNG": ("Qing Empire", "#e0b000", "Qing Dynasty"),
    "KOR": ("Korea", "#4169e1", None),
    "JAP": ("Japan", "#b22222", "jp"),
    "RYU": ("Ryukyu", None, None),
    "BRM": ("Burma", "#e9c46a", "Burma"),
    "SIA": ("Siam", "#48cae4", "Siam"),
    "DNA": ("Đại Nam", "#c9184a", None),
    "JOH": ("Johor", None, "Johor"),
    "PAH": ("Pahang", None, "Pahang"),
    "PRK": ("Perak", None, "Perak"),
    "SEL": ("Selangor", None, "Selangor"),
    "TRE": ("Terengganu", None, "Terengganu"),
    "KEL": ("Kelantan", None, "Kelantan"),
    "ACE": ("Aceh", None, "Aceh"),
    "BAL": ("Bali", None, None),
    "BRN": ("Brunei", None, "bn"),
    "SUL": ("Sulu", None, None),
    "MAG": ("Maguindanao", None, None),
    # Africa
    "SOK": ("Sokoto Caliphate", "#2a9d8f", None),
    "BOR": ("Bornu", None, None),
    "WAD": ("Wadai", None, None),
    "BAG": ("Bagirmi", None, None),
    "DAR": ("Darfur", None, "Darfur"),
    "OYO": ("Oyo", None, None),
    "BNN": ("Benin", None, "Kingdom of Benin"),
    "DAH": ("Dahomey", None, "Kingdom of Dahomey"),
    "ASH": ("Ashanti", "#f4d35e", None),
    "KNG": ("Kong", None, None),
    "MOS": ("Mossi States", None, None),
    "SEG": ("Ségou", None, None),
    "MAS": ("Massina", None, None),
    "KAA": ("Kaarta", None, None),
    "FUT": ("Futa Toro", None, None),
    "FJA": ("Futa Jallon", None, None),
    "LIB": ("Liberia", None, "lr"),
    "KGO": ("Kingdom of Kongo", None, "Kingdom of Kongo"),
    "KAS": ("Kasanje", None, None),
    "LUN": ("Lunda", None, None),
    "LBA": ("Luba", None, None),
    "KUB": ("Kuba", None, None),
    "KZB": ("Kazembe", None, None),
    "LOZ": ("Lozi", None, None),
    "ETH": ("Ethiopia", "#6a4c93", "Ethiopian Empire"),
    "SHE": ("Shewa", None, None),
    "HAR": ("Harar", None, None),
    "KAF": ("Kaffa", None, None),
    "BUG": ("Buganda", None, None),
    "BNY": ("Bunyoro", None, None),
    "NKO": ("Nkore", None, None),
    "KAR": ("Karagwe", None, None),
    "RWA": ("Rwanda", None, "rw"),
    "BRD": ("Burundi", None, "bi"),
    "MER": ("Merina", "#8338ec", "Merina Kingdom"),
    "SAK": ("Sakalava", None, None),
    "GAZ": ("Gaza Empire", None, None),
    "ZUL": ("Zulu Kingdom", "#1b4332", None),
    "XHO": ("Xhosa", None, None),
    "SOT": ("Basotho", None, "ls"),
    "SWZ": ("Swazi", None, "sz"),
    "NDE": ("Mthwakazi (Ndebele)", None, None),
    "GRI": ("Griqua States", None, None),
    # Oceania
    "MAO": ("Māori (United Tribes)", "#264653", "United Tribes of New Zealand"),
    "HAW": ("Kingdom of Hawaii", None, "Hawaii"),
    "TAH": ("Tahiti", None, None),
    "TON": ("Tonga", None, "to"),
    "FIJ": ("Fiji (Bau)", None, "fj"),
    "SAM": ("Samoa", None, "ws"),
}

# 1815 polity -> nation. Unlisted polities (Aboriginal groups, stateless
# peoples) start unowned.
POLITIES = {
    "Russian Empire": "RUS",
    "United Kingdom of Great Britain and Ireland": "GBR",
    "France": "FRA",
    "Spain": "SPA",
    "Guanches": "SPA",
    "Portugal": "POR",
    "United Kingdom of Netherlands": "NED",
    "Luxembourg": "LUX",
    "Switzerland": "SWI",
    "Denmark": "DEN",
    "Holstein": "DEN",
    "Schleswig": "DEN",
    "Sweden–Norway": "SWE",
    "Prussia": "PRU",
    "Wetzlar": "PRU",
    "Austrian Empire": "AUS",
    "Venetia": "AUS",
    "Lombardy": "AUS",
    "Bavaria": "BAV",
    "Palatinate": "BAV",
    "Württemberg": "WUR",
    "Baden": "BAD",
    "Saxony": "SAX",
    "Hanover": "HAN",
    "Electoral Hesse": "HKA",
    "Grand Duchy of Hesse": "HDA",
    "Nassau": "NAS",
    "Brunswick": "BRU",
    "Oldenburg": "OLD",
    "Mecklenburg-Schwerin": "MEC",
    "Mecklenburg-Strelitz": "MST",
    "Thuringia": "THU",
    "Anhalt": "ANH",
    "Lippe-Detmold": "LIP",
    "Schaumburg-Lippe": "LIP",
    "Waldeck": "WDK",
    "Hohenzollern": "HOH",
    "Hamburg": "HAM",
    "Cuxhaven": "HAM",
    "Bremen": "BRE",
    "Lübeck": "LUB",
    "Kingdom of Sardinia": "SAR",
    "Modena": "MOD",
    "Massa": "MOD",
    "Parma": "PMA",
    "Lucca": "LUC",
    "Tuscany": "TUS",
    "Fivizzano": "TUS",
    "Pontremoli": "TUS",
    "Papal States": "PAP",
    "San Marino": "SMR",
    "Kingdom of the Two Sicilies": "SIC",
    "Republic of Kraków": "KRA",
    "Ottoman Empire": "OTT",
    "Tripolitania": "OTT",
    "Cyrenaica": "OTT",
    "Persia": "PRS",
    "Afghanistan": "AFG",
    "Turan": "BUK",
    "Manchu Empire": "QNG",
    "Hong Kong": "QNG",
    "Japan": "JAP",
    "Korea": "KOR",
    "Maratha Confederacy": "EIC",
    "British East India Company": "EIC",
    "Assam": "EIC",
    "Arakan": "EIC",
    "Mysore (Indian princely state)": "MYS",
    "Travancore": "TRV",
    "Oudh": "OUD",
    "Sikkim (Indian princely state)": "SIK",
    "Nepal": "NEP",
    "Bhutan": "BHU",
    "Goa": "POR",
    "Ceylon": "GBR",
    "Burma": "BRM",
    "Rattanakosin Kingdom": "SIA",
    "Annam": "DNA",
    "Cochin China": "DNA",
    "Cambodia": "DNA",
    "Brunei": "BRN",
    "Dutch East Indies": "NED",
    "Minang": "NED",
    "Philippines": "SPA",
    "Nejd": "NEJ",
    "Yemen": "YEM",
    "Oman": "OMA",
    "Zanzibar": "OMA",
    "Egypt": "EGY",
    "Morocco": "MOR",
    "Algiers": "ABD",
    "Tunis": "TUN",
    "Fulani Empire": "SOK",
    "Kaarta": "KAA",
    "Mossi States": "MOS",
    "Asante": "ASH",
    "Fante": "GBR",
    "Kanem-Bornu": "BOR",
    "Sierra Leone": "GBR",
    "Portuguese Guinea": "POR",
    "Congo": "KGO",
    "Angola": "POR",
    "Imbangala": "KAS",
    "Lunda": "LUN",
    "Kazembe": "KZB",
    "Lozi": "LOZ",
    "Portuguese East Africa": "POR",
    "Delagoa Bay": "POR",
    "Ethiopia": "ETH",
    "Buganda": "BUG",
    "Bunyoro": "BNY",
    "Nkore": "NKO",
    "Rwanda": "RWA",
    "Burundi": "BRD",
    "Zulu": "ZUL",
    "Xhosa": "XHO",
    "Cape Colony": "GBR",
    "Merina Kingdom": "MER",
    "United States": "USA",
    "Canada": "GBR",
    "Viceroyalty of New Spain": "MEX",
    "Maya": "MEX",
    "Viceroyalty of New Granada": "NGR",
    "Viceroyalty of Peru": "PER",
    "United Provinces of the Río de la Plata": "ARG",
    "Paraguay": "PGY",
    "Viceroyalty of Brazil": "BRZ",
    "Guiana": "NED",
    "Haiti": "HAI",
    "United Kingdom": "GBR",
    "Trinidad": "GBR",
    "Guadeloupe": "FRA",
    "Martinique": "FRA",
    "New South Wales": "GBR",
    "Maori": "MAO",
    "Kingdom of Hawaii": "HAW",
}


def RULES(C, A, P, B, ALL):
    """(tag, selector) in order; the last match wins."""
    vojvodina = A("SRB", "Severno-Backi", "Južno-Backi", "Zapadno-Backi", "Srednje-Banatski",
                  "Severno-Banatski", "Južno-Banatski", "Sremski")
    return [
        # ---------------------------------------------------------------- Europe
        ("NOR", C("NOR")),
        ("-", A("NOR", "Svalbard")),
        ("BEL", C("BEL")),
        ("FIN", P("Russian Empire") & C("FIN", "ALD")),
        ("POL", P("Russian Empire") & C("POL")),
        ("DEN", C("ISL", "FRO", "GRL")),
        ("GBR", C("GIB", "MLT")),
        ("CAR", A("ESP", "Navarra", "Álava", "Gipuzkoa", "Bizkaia")),
        # Savoy and the County of Nice (east of the Var) were Sardinian until 1860.
        ("SAR", A("FRA", "Savoie", "Haute-Savoie") | (A("FRA", "Alpes-Maritimes") & B(7.19, 43.5, 8.0, 44.4))),
        ("FRK", C("DEU") & B(8.45, 50.02, 8.85, 50.22)),
        ("AUS", vojvodina),
        ("SER", C("SRB") & ~vojvodina & B(18.8, 43.45, 23.1, 45.0)),
        ("WAL", A("ROU", "Dolj", "Gorj", "Mehedinti", "Olt", "Vâlcea", "Arges", "Teleorman", "Giurgiu",
                  "Dâmbovita", "Prahova", "Ilfov", "Bucharest", "Ialomita", "Calarasi", "Buzau", "Braila")),
        ("MOL", A("ROU", "Iasi", "Botosani", "Neamt", "Bacau", "Vaslui", "Galati", "Vrancea")),
        ("OTT", A("ROU", "Constanta", "Tulcea")),
        ("MON", A("MNE", "Cetinje", "Danilovgrad", "Šavnik", "Žabljak")),
        ("GRE", C("GRC") & B(19.3, 34.5, 29.0, 39.15)),
        ("OTT", A("GRC", "Voreio Aigaio") | (A("GRC", "Notio Aigaio") & B(26.3, 35.3, 28.6, 37.6))),
        ("GBR", A("GRC", "Ionioi Nisoi")),
        ("EGY", A("GRC", "Kriti")),
        ("RUS", C("GEO", "ARM", "AZE")),
        ("OTT", A("GEO", "Ajaria")),
        ("IMA", A("RUS", "Dagestan", "Chechnya")),
        ("-", A("RUS", "Adygey", "Karachay-Cherkess") | (A("RUS", "Krasnodar") & B(36.5, 43.3, 41.0, 45.0))),
        ("-", A("RUS", "Sakhalin")),
        # ----------------------------------------------------- Middle East
        ("EGY", C("SYR", "LBN", "ISR", "PSX", "JOR") | A("TUR", "Adana", "Mersin", "Osmaniye", "Hatay")),
        ("EGY", A("SAU", "Makkah", "Al Madinah", "Al Bahah", "Tabuk", "`Asir", "Jizan")),
        ("-", A("SAU", "Al Jawf", "Al Hudud ash Shamaliyah")),
        ("KUW", C("KWT")),
        ("BAH", C("BHR", "QAT")),
        ("TRU", C("ARE")),
        ("LAH", A("YEM", "Lahij", "`Adan", "Abyan")),
        ("HAD", A("YEM", "Hadramawt", "Shabwah", "Al Mahrah")),
        ("OTT", C("IRQ")),
        # ------------------------------------------------------- Central Asia
        ("RUS", A("KAZ", "North Kazakhstan", "Pavlodar", "Aqmola", "Astana", "Qostanay", "East Kazakhstan",
                  "West Kazakhstan", "Aqtöbe", "Qaraghandy", "Atyrau", "Mangghystau")),
        ("KOK", A("KAZ", "South Kazakhstan", "Zhambyl", "Qyzylorda")),
        ("KZH", A("KAZ", "Almaty", "Almaty City")),
        ("KHI", A("UZB", "Khorezm", "Karakalpakstan") | A("TKM", "Tashauz")),
        ("BUK", A("UZB", "Bukhoro", "Navoi", "Samarkand", "Kashkadarya", "Surkhandarya", "Jizzakh")
                | A("TKM", "Chardzhou") | C("TJK")),
        ("KOK", A("UZB", "Tashkent", "Sirdaryo", "Ferghana", "Andijon", "Namangan") | A("TJK", "Leninabad")
                | C("KGZ")),
        ("-", A("TJK", "Gorno-Badakhshan") | A("TKM", "Ahal", "Balkan", "Mary")),
        ("AFG", C("AFG")),
        ("HER", A("AFG", "Hirat", "Badghis", "Farah", "Nimroz", "Ghor")),
        ("KDH", A("AFG", "Kandahar", "Hilmand", "Uruzgan", "Zabul")),
        ("KUN", A("AFG", "Kunduz", "Takhar", "Baghlan", "Badakhshan", "Balkh", "Samangan")),
        ("-", A("AFG", "Nuristan", "Bamyan", "Jawzjan", "Faryab", "Sari Pul")),
        # --------------------------------------------------------- South Asia
        ("PUN", A("PAK", "Punjab", "K.P.", "F.C.T.", "Azad Kashmir")),
        ("BHW", A("PAK", "Punjab") & B(69.3, 27.5, 74.2, 30.05)),
        ("SND", A("PAK", "Sind")),
        ("KAL", A("PAK", "Baluchistan")),
        ("-", A("PAK", "F.A.T.A.", "Northern Areas")),
        ("EIC", C("IND", "BGD")),
        ("GBR", C("LKA")),
        ("-", A("IND", "Arunachal Pradesh", "Nagaland", "Mizoram", "Meghalaya", "Andaman and Nicobar")),
        ("MNP", A("IND", "Manipur")),
        ("SIK", A("IND", "Sikkim")),
        ("PUN", A("IND", "Jammu and Kashmir", "Ladakh") | (A("IND", "Punjab") & B(73.8, 31.0, 76.0, 33.0))
                | (A("IND", "Himachal Pradesh") & B(75.9, 31.7, 76.8, 32.6))),
        ("RAJ", A("IND", "Rajasthan")),
        ("BAR", A("IND", "Gujarat")),
        ("HYD", A("IND", "Telangana") | (A("IND", "Maharashtra") & B(75.0, 18.0, 78.2, 20.5))
                | (A("IND", "Maharashtra") & B(76.0, 20.5, 78.2, 21.5))
                | (A("IND", "Karnataka") & B(76.3, 15.4, 78.0, 18.5))),
        ("NAG", A("IND", "Chhattisgarh") | (A("IND", "Maharashtra") & B(78.2, 18.5, 81.0, 22.0))),
        ("GWA", A("IND", "Madhya Pradesh") & (B(74.0, 24.4, 79.2, 27.0) | B(75.0, 22.8, 76.2, 24.4))),
        ("HOL", A("IND", "Madhya Pradesh") & B(74.0, 21.0, 76.6, 22.8)),
        ("BHO", A("IND", "Madhya Pradesh") & B(76.6, 22.4, 78.2, 23.9)),
        ("OUD", P("Oudh")),
        ("MYS", P("Mysore (Indian princely state)")),
        ("TRV", A("IND", "Kerala") & B(76.0, 8.0, 77.5, 10.7)),
        ("POR", A("IND", "Goa", "Dadra and Nagar Haveli and Daman and Diu")),
        ("FRA", A("IND", "Puducherry")),
        # ------------------------------------------------- East Asia
        ("QNG", C("CHN", "MNG", "TWN", "HKG")),
        ("POR", C("MAC")),
        ("QNG", A("RUS", "Tuva") | (A("RUS", "Primor'ye", "Amur", "Khabarovsk") & B(126.0, 42.0, 142.0, 55.0))),
        ("KOR", C("KOR", "PRK")),
        ("JAP", C("JPN")),
        ("RYU", A("JPN", "Okinawa")),
        # --------------------------------------------- Southeast Asia
        ("BRM", C("MMR")),
        ("EIC", A("MMR", "Rakhine", "Tanintharyi") | (A("MMR", "Mon") & B(97.3, 14.5, 98.6, 16.6))),
        ("SIA", C("THA", "LAO") | A("MYS", "Kedah", "Perlis")),
        ("DNA", C("KHM", "VNM") | A("LAO", "Xiangkhoang", "Houaphan")),
        ("SIA", A("KHM", "Batdâmbâng", "Bântéay Méanchey", "Siemréab", "Otdar Mean Chey", "Krong Pailin")),
        ("JOH", A("MYS", "Johor")),
        ("PAH", A("MYS", "Pahang")),
        ("PRK", A("MYS", "Perak")),
        ("SEL", A("MYS", "Selangor", "Kuala Lumpur", "Putrajaya", "Negeri Sembilan")),
        ("TRE", A("MYS", "Terengganu")),
        ("KEL", A("MYS", "Kelantan")),
        ("GBR", A("MYS", "Pulau Pinang", "Melaka") | C("SGP")),
        ("BRN", C("BRN") | A("MYS", "Sarawak", "Labuan")),
        ("SUL", A("MYS", "Sabah")),
        ("NED", C("IDN")),
        ("-", A("IDN", "Papua", "Papua Barat", "Kalimantan Barat", "Kalimantan Tengah", "Kalimantan Timur",
                "Sulawesi Tengah", "Sulawesi Tenggara", "Sulawesi Barat", "Sumatera Utara", "Riau", "Jambi")),
        ("ACE", A("IDN", "Aceh")),
        ("BAL", A("IDN", "Bali", "Nusa Tenggara Barat")),
        ("POR", C("TLS")),
        ("SPA", C("PHL")),
        ("SUL", A("PHL", "Sulu", "Basilan")),
        ("MAG", A("PHL", "Maguindanao", "Lanao del Sur", "Lanao del Norte", "Cotabato")),
        ("-", C("PHL") & B(125.0, 5.5, 126.7, 7.9)),
        ("-", C("PNG")),
        # --------------------------------------------------------------- Africa
        ("MOR", C("MAR")),
        ("-", A("MAR", "Laâyoune - Boujdour - Sakia El Hamra", "Oued el Dahab")),
        ("FRA", A("DZA", "Alger", "Blida", "Boumerdès", "Tipaza", "Oran", "Mostaganem", "Annaba", "El Tarf",
                  "Béjaïa")),
        ("CON", A("DZA", "Constantine", "Mila", "Jijel", "Skikda", "Guelma", "Souk Ahras", "Oum el Bouaghi",
                  "Khenchela", "Batna", "Sétif", "Bordj Bou Arréridj", "M'Sila", "Tébessa", "Biskra")),
        ("-", A("DZA", "Tizi Ouzou", "Bouira", "Adrar", "Tamanghasset", "Illizi", "Ouargla", "Ghardaïa",
                "El Oued", "Béchar", "Tindouf", "Naâma", "Laghouat", "Djelfa", "El Bayadh")),
        ("TUN", C("TUN")),
        ("-", A("LBY", "Sabha", "Murzuq", "Ghat", "Wadi al Hayaa", "Ash Shati'", "Al Kufrah", "Al Jufrah")),
        ("EGY", C("EGY") | A("SDN", "Northern", "River Nile", "Khartoum", "Gezira", "Sennar", "White Nile",
                             "North Kordufan", "Blue Nile")),
        ("DAR", A("SDN", "North Darfur", "Southern Darfur", "Western Darfur", "Central Darfur",
                  "Eastern Darfur")),
        ("-", A("SDN", "Red Sea", "Kassala", "Gedarif", "South Kordufan") | C("SDS")),
        ("WAD", A("TCD", "Ouaddaï", "Wadi Fira", "Sila", "Batha")),
        ("BAG", A("TCD", "Chari-Baguirmi", "Hadjer-Lamis", "Guéra")),
        ("BOR", A("TCD", "Kanem", "Lac", "Barh El Gazel", "Ville de N'Djamena") | A("NER", "Diffa", "Zinder")
                | A("NGA", "Borno", "Yobe") | A("CMR", "Extrême-Nord")),
        ("-", A("TCD", "Borkou", "Ennedi", "Tibesti") | A("NER", "Agadez")),
        ("SOK", A("NGA", "Sokoto", "Kebbi", "Zamfara", "Katsina", "Kano", "Jigawa", "Kaduna", "Bauchi", "Gombe",
                  "Adamawa", "Niger", "Kwara", "Nassarawa", "Federal Capital Territory", "Taraba")
                | A("CMR", "Adamaoua", "Nord")),
        ("OYO", A("NGA", "Oyo", "Osun", "Ogun", "Ekiti", "Ondo", "Lagos")),
        ("BNN", A("NGA", "Edo", "Delta")),
        ("-", A("NGA", "Anambra", "Enugu", "Ebonyi", "Imo", "Abia", "Rivers", "Bayelsa", "Akwa Ibom",
                "Cross River", "Benue", "Kogi", "Plateau")),
        ("DAH", A("BEN", "Zou", "Collines", "Atlantique", "Littoral", "Ouémé", "Plateau", "Mono", "Kouffo")),
        ("-", A("BEN", "Borgou", "Alibori", "Atakora", "Donga") | C("TGO")),
        ("ASH", C("GHA")),
        ("GBR", A("GHA", "Central", "Greater Accra")),
        ("-", A("GHA", "Volta")),
        ("KNG", A("CIV", "Savanes", "Denguélé", "Worodougou", "Vallée du Bandama", "Zanzan")),
        ("SEG", A("MLI", "Ségou", "Koulikoro", "Bamako")),
        ("MAS", A("MLI", "Mopti", "Timbuktu")),
        ("KAA", A("MLI", "Kayes")),
        ("-", A("MLI", "Gao", "Kidal", "Sikasso")),
        ("-", C("SEN", "MRT")),
        ("FUT", A("SEN", "Matam") | (A("SEN", "Saint-Louis") & B(-15.0, 15.8, -13.0, 16.7))
                | (C("MRT") & B(-14.8, 15.0, -12.2, 16.8))),
        ("FRA", A("SEN", "Dakar") | (C("SEN") & B(-16.6, 15.9, -16.3, 16.2))),
        ("GBR", C("GMB")),
        ("FJA", A("GIN", "Labé", "Mamou", "Pita", "Dalaba", "Tougué", "Koubia", "Lélouma", "Mali", "Gaoual",
                  "Dinguiraye")),
        ("LIB", C("LBR") & B(-11.4, 5.7, -9.4, 6.9)),
        ("LBA", A("COD", "Kasaï-Oriental") | (A("COD", "Katanga") & B(24.0, -8.0, 28.0, -5.0))),
        ("KUB", A("COD", "Kasaï-Occidental") & B(20.5, -5.5, 23.0, -3.5)),
        ("-", A("ETH", "Afar", "Somali", "Gambela Peoples", "Benshangul-Gumaz")),
        ("SHE", A("ETH", "Addis Ababa") | (A("ETH", "Amhara") & B(38.5, 9.0, 40.5, 10.8))
                | (A("ETH", "Oromiya") & B(37.8, 8.6, 40.0, 9.8))),
        ("HAR", A("ETH", "Harari People", "Dire Dawa")),
        ("KAF", A("ETH", "Southern Nations, Nationalities and Peoples") & B(35.5, 6.8, 37.0, 7.8)),
        ("OTT", A("ERI", "Semenawi Keyih Bahri", "Debubawi Keyih Bahri")),
        ("OMA", A("TZA", "Kaskazini-Pemba", "Kusini-Pemba", "Kaskazini-Unguja", "Zanzibar South and Central",
                  "Zanzibar West")),
        ("KAR", A("TZA", "Kagera")),
        ("GAZ", A("MOZ", "Gaza", "Inhambane") | (A("MOZ", "Manica") & B(32.5, -21.5, 34.5, -19.0))),
        ("SAK", A("MDG", "Menabe", "Melaky")),
        ("GBR", A("ZAF", "Western Cape") | (A("ZAF", "Eastern Cape") & B(22.0, -34.5, 27.5, -30.5))
                | (A("ZAF", "Northern Cape") & B(17.0, -32.5, 24.5, -30.5))),
        ("XHO", A("ZAF", "Eastern Cape") & B(27.5, -33.5, 29.8, -30.8)),
        ("ZUL", A("ZAF", "KwaZulu-Natal") & B(29.5, -29.5, 32.9, -26.8)),
        ("SWZ", C("SWZ")),
        ("SOT", C("LSO") | (A("ZAF", "Free State") & B(27.0, -30.2, 28.9, -28.5))),
        ("NDE", A("ZAF", "North West", "Gauteng")),
        ("GRI", (A("ZAF", "Northern Cape") & B(22.0, -29.5, 25.5, -28.0))
                | (A("ZAF", "Free State") & B(24.8, -30.5, 26.0, -29.3))),
        # -------------------------------------------------------------- Oceania
        ("-", C("AUS")),
        ("GBR", A("AUS", "Tasmania", "Australian Capital Territory", "Jervis Bay Territory")
                | (A("AUS", "New South Wales") & B(148.5, -35.8, 152.6, -31.3))
                | (A("AUS", "Western Australia") & B(115.2, -32.8, 116.8, -31.3))
                | (A("AUS", "Victoria") & B(144.3, -38.4, 145.3, -37.5))
                | (A("AUS", "Queensland") & B(152.4, -27.8, 153.2, -27.0))),
        ("MAO", C("NZL")),
        ("HAW", A("USA", "Hawaii")),
        ("TAH", C("PYF")),
        ("TON", C("TON")),
        ("FIJ", C("FJI")),
        ("SAM", C("WSM", "ASM")),
        # ------------------------------------------------------------- Americas
        ("-", A("CAN", "Nunavut", "Northwest Territories") & B(-141.0, 69.0, -60.0, 84.0)),
        ("RUS", A("USA", "Alaska")),
        ("-", A("USA", "Oregon", "Washington", "Idaho") | (A("CAN", "British Columbia") & B(-140.0, 48.0, -114.0, 54.67))
              | (A("USA", "Montana") & B(-117.0, 44.0, -111.5, 49.1))
              | (A("USA", "Wyoming") & B(-111.1, 42.0, -109.5, 45.1))),
        ("MEX", A("USA", "California", "Nevada", "Utah", "Arizona", "New Mexico")
                | (A("USA", "Colorado") & (B(-110.0, 36.0, -106.3, 42.0) | B(-110.0, 36.0, -100.0, 38.3)))
                | (A("USA", "Wyoming") & B(-112.0, 40.0, -106.3, 42.0))
                | (A("USA", "Kansas") & B(-102.1, 36.9, -100.0, 38.0))
                | (A("USA", "Oklahoma") & B(-103.1, 36.5, -100.0, 37.1))),
        ("TEX", A("USA", "Texas")),
        ("COM", (A("USA", "Texas") & B(-103.1, 30.8, -98.5, 36.6)) | (A("USA", "New Mexico") & B(-104.5, 32.0, -103.0, 37.0))
                | (A("USA", "Oklahoma") & B(-100.0, 34.0, -98.0, 36.5))),
        ("SEM", A("USA", "Florida") & B(-83.0, 24.5, -80.0, 28.6)),
        ("LAK", (A("USA", "South Dakota") & B(-104.1, 42.4, -100.0, 45.95))
                | (A("USA", "Nebraska") & B(-104.1, 41.8, -101.0, 43.0))
                | (A("USA", "Wyoming") & B(-106.3, 42.0, -104.0, 45.0))
                | (A("USA", "Montana") & B(-108.0, 44.9, -104.0, 46.5))),
        ("MEX", C("MEX")),
        ("UCA", C("GTM", "HND", "SLV", "NIC", "CRI")),
        ("GBR", C("BLZ")),
        ("MSQ", (C("NIC") & B(-84.8, 10.9, -83.0, 15.1)) | (C("HND") & B(-85.8, 14.5, -83.1, 16.0))),
        ("SPA", C("CUB", "PRI")),
        ("HAI", C("HTI", "DOM")),
        ("GBR", C("JAM", "BHS", "TCA", "CYM", "VGB", "AIA", "ATG", "KNA", "MSR", "DMA", "LCA", "VCT", "GRD",
                  "BRB", "TTO", "BMU")),
        ("FRA", A("FRA", "Guadeloupe", "Martinique", "Guyane française")),
        ("NED", C("ABW", "CUW", "SXM", "SUR")),
        ("GBR", C("GUY", "FLK")),
        ("NGR", C("COL", "PAN")),
        ("VEN", C("VEN")),
        ("ECU", C("ECU")),
        ("PER", C("PER") | A("CHL", "Arica y Parinacota", "Tarapacá")),
        ("BOL", C("BOL") | A("CHL", "Antofagasta")),
        ("CHL", C("CHL") & ~A("CHL", "Arica y Parinacota", "Tarapacá", "Antofagasta")),
        ("-", A("CHL", "Aisén del General Carlos Ibáñez del Campo", "Magallanes y Antártica Chilena")
              | (A("CHL", "Los Lagos") & B(-76.0, -44.5, -71.0, -41.9) & ~B(-74.5, -43.5, -73.3, -41.7))),
        ("ARG", C("ARG")),
        ("-", A("ARG", "Chaco", "Formosa", "Misiones", "La Pampa", "Río Negro", "Chubut", "Santa Cruz",
                "Tierra del Fuego") | (A("ARG", "Buenos Aires") & B(-63.5, -41.5, -56.0, -36.3))
              | (A("ARG", "Córdoba", "San Luis", "Mendoza") & B(-70.5, -37.0, -62.0, -34.3))),
        ("MAP", A("CHL", "La Araucanía") | (A("CHL", "Bío-Bío") & B(-73.8, -38.5, -71.0, -37.3))
                | A("ARG", "Neuquén")),
        ("URU", C("URY")),
        ("PGY", C("PRY")),
        ("BRZ", C("BRA")),
        ("-", A("BRA", "Amazonas", "Acre", "Roraima", "Rondônia")),
        # Antarctica: the nearest-country fill would hand it to Chile and Norway.
        ("-", B(-180, -90, 180, -60)),
    ]


# Capital towns, where the nation's biggest town today (GeoNames) isn't its
# 1836 capital, or is a colony's. The rest take their biggest; None means no
# city (peoples without towns). ponytail: many small nations' biggest town is
# modern (Johannesburg, Lilongwe) until ROADMAP 3.6's names and founding years.
CAPITALS = {
    "MEX": "Mexico City",
    "MOR": "Fes",
    "HAN": "Hannover",
    "EGY": "Cairo",
    "ASH": "Kumasi",
    "COM": None,
    "LAK": None,
    "SEM": None,
    "MAP": None,
    "RUS": "Saint Petersburg",
    "USA": "Washington",
    "QNG": "Beijing",
    "BRZ": "Rio de Janeiro",
    "EIC": "Kolkata",
    "GBR": "London",
    "NED": "Amsterdam",
    "SPA": "Madrid",
    "POR": "Lisbon",
    "OMA": "Muscat",
    "SWI": "Bern",
    "AUS": "Vienna",
    "DEN": "Copenhagen",
    "SAX": "Dresden",
    "BAD": "Karlsruhe",
    "SER": "Kragujevac",
    "FRA": "Paris",
    "OTT": "Istanbul",
}

# The Holy Alliance, the Quadruple Alliance, and the unions and vassals the
# engine can't show yet (SANDBOX.md F6) as alliances.
ALLIANCES = [
    ("RUS", "AUS", "PRU"),
    ("GBR", "FRA", "SPA", "POR"),
    ("RUS", "FIN"),
    ("RUS", "POL"),
    ("SWE", "NOR"),
    ("NED", "LUX"),
    ("OTT", "SER"),
    ("OTT", "WAL"),
    ("OTT", "MOL"),
    ("OTT", "TUN"),
    ("EIC", "HYD"),
    ("EIC", "OUD"),
    ("EIC", "MYS"),
    ("EIC", "TRV"),
    ("EIC", "GWA"),
    ("EIC", "HOL"),
    ("EIC", "BAR"),
    ("EIC", "NAG"),
    ("EIC", "BHO"),
    ("EIC", "RAJ"),
    ("GBR", "EIC"),
    ("QNG", "KOR"),
    ("QNG", "RYU"),
    ("SIA", "KEL"),
    ("SIA", "TRE"),
]

# Town positions (lon, lat) where the World map's coast is off: it draws
# Zealand's east shore ~0.3 degrees west, so the real Copenhagen is in the sea
# next to Sweden. Lisbon's own tile is its neighbour's.
TOWN_AT = {"Copenhagen": (12.3, 55.68), "Lisbon": (-9.0, 38.76)}

# (town, GeoNames country code, owner): ROADMAP.md 3.3 plus capitals.
CHECKS = [
    ("Istanbul", "TR", "OTT"), ("Warsaw", "PL", "POL"), ("Kraków", "PL", "KRA"), ("Poznań", "PL", "PRU"),
    ("Lviv", "UA", "AUS"), ("Milan", "IT", "AUS"), ("Turin", "IT", "SAR"), ("Nice", "FR", "SAR"),
    ("Chambéry", "FR", "SAR"), ("Rome", "IT", "PAP"), ("Naples", "IT", "SIC"), ("Florence", "IT", "TUS"),
    ("Brussels", "BE", "BEL"),
    ("Athens", "GR", "GRE"), ("Thessaloniki", "GR", "OTT"), ("Belgrade", "RS", "SER"), ("Bucharest", "RO", "WAL"),
    ("Algiers", "DZ", "FRA"), ("Cairo", "EG", "EGY"), ("Damascus", "SY", "EGY"), ("Tunis", "TN", "TUN"),
    ("San Antonio", "US", "TEX"), ("Santa Fe", "US", "MEX"), ("Monterey", "US", "MEX"), ("Juneau", "US", "RUS"),
    ("Guatemala City", "GT", "UCA"), ("Panama", "PA", "NGR"), ("Santo Domingo", "DO", "HAI"),
    ("Havana", "CU", "SPA"), ("Lahore", "PK", "PUN"), ("Peshawar", "PK", "PUN"), ("Karachi", "PK", "SND"),
    ("Hyderabad", "IN", "HYD"), ("Lucknow", "IN", "OUD"), ("Kathmandu", "NP", "NEP"), ("Kabul", "AF", "AFG"),
    ("Herat", "AF", "HER"), ("Tbilisi", "GE", "RUS"), ("Bukhara", "UZ", "BUK"), ("Kashgar", "CN", "QNG"),
    ("Vladivostok", "RU", "QNG"), ("Seoul", "KR", "KOR"), ("Taipei", "TW", "QNG"), ("Hanoi", "VN", "DNA"),
    ("Phnom Penh", "KH", "DNA"), ("Bangkok", "TH", "SIA"), ("Yangon", "MM", "BRM"), ("Singapore", "SG", "GBR"),
    ("Jakarta", "ID", "NED"), ("Manila", "PH", "SPA"), ("Honolulu", "US", "HAW"), ("Sydney", "AU", "GBR"),
    ("Auckland", "NZ", "MAO"), ("Cape Town", "ZA", "GBR"), ("Antananarivo", "MG", "MER"),
    ("Kumasi", "GH", "ASH"), ("Sokoto", "NG", "SOK"), ("Helsinki", "FI", "FIN"), ("Oslo", "NO", "NOR"),
    # Capitals and more
    ("London", "GB", "GBR"), ("Paris", "FR", "FRA"), ("Vienna", "AT", "AUS"), ("Berlin", "DE", "PRU"),
    ("Munich", "DE", "BAV"), ("Dresden", "DE", "SAX"), ("Hanover", "DE", "HAN"), ("Stuttgart", "DE", "WUR"),
    ("Madrid", "ES", "SPA"), ("Lisbon", "PT", "POR"), ("Amsterdam", "NL", "NED"), ("Copenhagen", "DK", "DEN"),
    ("Stockholm", "SE", "SWE"), ("Moscow", "RU", "RUS"), ("Saint Petersburg", "RU", "RUS"),
    ("Beijing", "CN", "QNG"), ("Tokyo", "JP", "JAP"), ("Tehran", "IR", "PRS"), ("Mexico City", "MX", "MEX"),
    ("New York City", "US", "USA"), ("Rio de Janeiro", "BR", "BRZ"), ("Buenos Aires", "AR", "ARG"),
    ("Lima", "PE", "PER"), ("Bogotá", "CO", "NGR"), ("Caracas", "VE", "VEN"), ("Santiago", "CL", "CHL"),
    ("La Paz", "BO", "BOL"), ("Montevideo", "UY", "URU"), ("Asunción", "PY", "PGY"), ("Quito", "EC", "ECU"),
    ("Delhi", "IN", "EIC"), ("Kolkata", "IN", "EIC"), ("Mumbai", "IN", "EIC"), ("Chennai", "IN", "EIC"),
    ("Colombo", "LK", "GBR"), ("Riyadh", "SA", "NEJ"), ("Muscat", "OM", "OMA"), ("Mecca", "SA", "EGY"),
    ("Baghdad", "IQ", "OTT"), ("Addis Ababa", "ET", "SHE"), ("Khartoum", "SD", "EGY"), ("Timbuktu", "ML", "MAS"),
    ("Tripoli", "LY", "OTT"), ("Rabat", "MA", "MOR"), ("Zanzibar", "TZ", "OMA"), ("Tashkent", "UZ", "KOK"),
    ("Khiva", "UZ", "KHI"), ("Kandahar", "AF", "KDH"), ("Mandalay", "MM", "BRM"), ("Hue", "VN", "DNA"),
    ("Kuala Lumpur", "MY", "SEL"), ("Banda Aceh", "ID", "ACE"), ("Denpasar", "ID", "BAL"),
    ("Luanda", "AO", "POR"), ("Sucre", "BO", "BOL"), ("Guayaquil", "EC", "ECU"), ("Porto Alegre", "BR", "BRZ"),
    ("Monrovia", "LR", "LIB"), ("Freetown", "SL", "GBR"), ("Oran", "DZ", "FRA"), ("Constantine", "DZ", "CON"),
    ("Tlemcen", "DZ", "ABD"), ("Mascara", "DZ", "ABD"), ("Maseru", "LS", "SOT"), ("Mbabane", "SZ", "SWZ"),
    ("Lagos", "NG", "OYO"), ("Kano", "NG", "SOK"), ("Benin City", "NG", "BNN"), ("Abomey", "BJ", "DAH"),
    ("Ségou", "ML", "SEG"), ("Harar", "ET", "HAR"), ("Gondar", "ET", "ETH"), ("Tbilisi", "GE", "RUS"),
    ("Ulaanbaatar", "MN", "QNG"), ("Lhasa", "CN", "QNG"), ("Almaty", "KZ", "KZH"), ("Makhachkala", "RU", "IMA"),
]
